sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ste5an/test-app -f Dockerfile .

script:
  - docker run -e CI=true ste5an/test-app

after_success:
  - docker build -t ste5an/test-app -f Dockerfile .
  - docker build -t s-t ste5an/pg -f Dockerfile .

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ste5an/test-app
  - docker push ste5an/pg

